//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_R47.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class items2
    {
        public int itemcode { get; set; }
        public string itemname { get; set; }
        public Nullable<int> deptid { get; set; }
        public Nullable<decimal> cost { get; set; }
        public Nullable<decimal> rate { get; set; }
    
        public virtual dept2 dept2 { get; set; }
    }
}
