//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_R47.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class cm_restoEntities : DbContext
    {
        public cm_restoEntities()
            : base("name=cm_restoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<detail> details { get; set; }
        public virtual DbSet<master> masters { get; set; }
        public virtual DbSet<item> items { get; set; }
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Cours> Courses { get; set; }
        public virtual DbSet<dept2> dept2 { get; set; }
        public virtual DbSet<Enrollment> Enrollments { get; set; }
        public virtual DbSet<Guradian5> Guradian5 { get; set; }
        public virtual DbSet<Instructor> Instructors { get; set; }
        public virtual DbSet<items2> items2 { get; set; }
        public virtual DbSet<OfficeAssignment> OfficeAssignments { get; set; }
        public virtual DbSet<student2> student2 { get; set; }
        public virtual DbSet<student5> student5 { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<sale> sales { get; set; }
    }
}
