//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_R47.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class cnstringEntities : DbContext
    {
        public cnstringEntities()
            : base("name=cnstringEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<foodMenuTB> foodMenuTBs { get; set; }
        public virtual DbSet<department> departments { get; set; }
        public virtual DbSet<item> items { get; set; }
        public virtual DbSet<party> parties { get; set; }
        public virtual DbSet<purchasedetail> purchasedetails { get; set; }
        public virtual DbSet<purchasemaster> purchasemasters { get; set; }
        public virtual DbSet<salesdetail> salesdetails { get; set; }
        public virtual DbSet<salesmaster> salesmasters { get; set; }
        public virtual DbSet<student2> student2 { get; set; }
    }
}
