//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_R47.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class salesmaster
    {
        public string vrno { get; set; }
        public Nullable<decimal> total { get; set; }
        public Nullable<decimal> discount { get; set; }
        public Nullable<decimal> net { get; set; }
        public Nullable<decimal> paid { get; set; }
        public Nullable<decimal> due { get; set; }
        public string PID { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    
        public virtual party party { get; set; }
    }
}
